[package]
name = "switchbot-meter-statsd"
version = "0.1.0"
authors = ["Jordan Yelloz <jordan@yelloz.me>"]
edition = "2021"
license = "MIT"

[dependencies]
zbus = "2"
anyhow = "*"
serde = "1"
cadence = "0.29"
